-- ============================================
-- background_job : 비동기 작업 발행 대기 테이블
-- ============================================
CREATE TABLE background_job (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type        VARCHAR2(100)             NOT NULL,
    member_id       NUMBER                    NOT NULL,
    job_data        CLOB                      NOT NULL,
    trace_id        VARCHAR2(100)             NOT NULL,
    idempotency_key VARCHAR2(100)             NOT NULL,
    request_hash    VARCHAR2(64)              NOT NULL,
    status          VARCHAR2(30)              NOT NULL,
    requested_at    TIMESTAMP WITH TIME ZONE  NOT NULL,
    started_at      TIMESTAMP WITH TIME ZONE,
    finished_at     TIMESTAMP WITH TIME ZONE,
    next_retry_at   TIMESTAMP WITH TIME ZONE,
    retry_count     NUMBER DEFAULT 0          NOT NULL,
    error_code      VARCHAR2(50),
    error_reason    VARCHAR2(255),
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      NUMBER,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      NUMBER,
    CONSTRAINT fk_background_job_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT uk_background_job_idempotency UNIQUE (member_id, job_type, idempotency_key)
);

CREATE INDEX idx_background_job_status_requested ON background_job (status, requested_at);
CREATE INDEX idx_background_job_next_retry ON background_job (next_retry_at);
CREATE INDEX idx_background_job_member_requested ON background_job (member_id, requested_at DESC);

-- ============================================
-- analysis_report : AI 분석 리포트
-- ============================================
CREATE TABLE analysis_report (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    background_job_id NUMBER                    NOT NULL,
    member_id         NUMBER                    NOT NULL,
    report_type       VARCHAR2(100)             NOT NULL,
    status            VARCHAR2(30)              NOT NULL,
    result            CLOB,
    provider          VARCHAR2(30),
    model             VARCHAR2(100),
    llm_options       CLOB,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        NUMBER,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        NUMBER,
    CONSTRAINT fk_analysis_report_job FOREIGN KEY (background_job_id) REFERENCES background_job(id),
    CONSTRAINT fk_analysis_report_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT uk_analysis_report_job UNIQUE (background_job_id)
);

CREATE INDEX idx_analysis_report_member_created ON analysis_report (member_id, created_at DESC);

-- ============================================
-- analysis_report_source : AI 리포트 소재 스냅샷
-- ============================================
CREATE TABLE analysis_report_source (
    id                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_report_id       NUMBER        NOT NULL,
    daily_question_answer_id NUMBER        NOT NULL,
    question_date            DATE          NOT NULL,
    question_content         VARCHAR2(500) NOT NULL,
    answer_content           CLOB          NOT NULL,
    seq_no                   NUMBER        NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE,
    created_by               NUMBER,
    updated_at               TIMESTAMP WITH TIME ZONE,
    updated_by               NUMBER,
    CONSTRAINT fk_ars_report FOREIGN KEY (analysis_report_id) REFERENCES analysis_report(id),
    CONSTRAINT fk_ars_daily_answer FOREIGN KEY (daily_question_answer_id) REFERENCES daily_question_answer(id),
    CONSTRAINT uk_ars_report_answer UNIQUE (analysis_report_id, daily_question_answer_id),
    CONSTRAINT uk_ars_report_seq UNIQUE (analysis_report_id, seq_no)
);

CREATE INDEX idx_ars_daily_answer ON analysis_report_source (daily_question_answer_id);
