-- ============================================
-- background_job : 비동기 작업 발행 대기 테이블
-- ============================================
CREATE TABLE background_job (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type        VARCHAR2(100)             NOT NULL,
    member_id       NUMBER                    NOT NULL,
    reference_id    NUMBER,
    payload         CLOB                      NOT NULL,
    correlation_id  VARCHAR2(100)             NOT NULL,
    idempotency_key VARCHAR2(100)             NOT NULL,
    request_hash    VARCHAR2(64)              NOT NULL,
    status          VARCHAR2(30)              NOT NULL,
    scheduled_at    TIMESTAMP WITH TIME ZONE  NOT NULL,
    started_at      TIMESTAMP WITH TIME ZONE,
    finished_at     TIMESTAMP WITH TIME ZONE,
    next_retry_at   TIMESTAMP WITH TIME ZONE,
    publish_claim_id    VARCHAR2(36),
    publish_claim_until TIMESTAMP WITH TIME ZONE,
    retry_count     NUMBER DEFAULT 0          NOT NULL,
    error_code      VARCHAR2(50),
    error_reason    VARCHAR2(255),
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      NUMBER,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      NUMBER,
    CONSTRAINT fk_background_job_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT uk_background_job_idempotency UNIQUE (member_id, job_type, idempotency_key)
);

COMMENT ON COLUMN background_job.reference_id IS
    'job_type이 가리키는 도메인 애그리거트의 id. 폴리모픽 참조이므로 FK 없음. 대상이 없는 job 타입은 NULL.';

-- 대상 애그리거트 1건당 job 1건.
-- reference_id 가 NULL 이면 두 표현식이 모두 NULL 이 되어 인덱스에서 제외된다
-- (Oracle 에서 partial unique index 를 만드는 관용구).
-- 엔티티에는 @UniqueConstraint(columnNames = {"job_type", "reference_id"}) 로 선언돼 있다.
-- 형태가 다른데도 부팅이 깨지지 않는 이유는 Hibernate ddl-auto=validate 가
-- 테이블/컬럼/타입만 검증하고 제약·인덱스는 보지 않기 때문이다.
-- PostgreSQL 로 이전하면 아래로 단순화할 수 있다:
--   CREATE UNIQUE INDEX uk_background_job_reference
--       ON background_job (job_type, reference_id) WHERE reference_id IS NOT NULL;
CREATE UNIQUE INDEX uk_background_job_reference ON background_job
    (CASE WHEN reference_id IS NULL THEN NULL ELSE job_type END, reference_id);

CREATE INDEX idx_background_job_status_scheduled ON background_job (status, scheduled_at);
CREATE INDEX idx_background_job_publish_claim ON background_job (status, publish_claim_until);

-- ============================================
-- analysis_report : AI 분석 리포트
-- ============================================
CREATE TABLE analysis_report (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         NUMBER                    NOT NULL,
    report_type       VARCHAR2(100)             NOT NULL,
    status            VARCHAR2(30)              NOT NULL,
    result            CLOB,
    provider          VARCHAR2(30),
    model             VARCHAR2(100),
    llm_options       CLOB,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        NUMBER,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        NUMBER,
    CONSTRAINT fk_analysis_report_member FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE INDEX idx_analysis_report_member_created ON analysis_report (member_id, created_at DESC);

-- ============================================
-- analysis_report_source : AI 리포트 소재 스냅샷
-- ============================================
CREATE TABLE analysis_report_source (
    id                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_report_id       NUMBER        NOT NULL,
    daily_question_answer_id NUMBER        NOT NULL,
    question_date            DATE          NOT NULL,
    question_content         VARCHAR2(500) NOT NULL,
    answer_content           CLOB          NOT NULL,
    seq_no                   NUMBER        NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE,
    created_by               NUMBER,
    updated_at               TIMESTAMP WITH TIME ZONE,
    updated_by               NUMBER,
    CONSTRAINT fk_ars_report FOREIGN KEY (analysis_report_id) REFERENCES analysis_report(id),
    CONSTRAINT fk_ars_daily_answer FOREIGN KEY (daily_question_answer_id) REFERENCES daily_question_answer(id),
    CONSTRAINT uk_ars_report_answer UNIQUE (analysis_report_id, daily_question_answer_id),
    CONSTRAINT uk_ars_report_seq UNIQUE (analysis_report_id, seq_no)
);

CREATE INDEX idx_ars_daily_answer ON analysis_report_source (daily_question_answer_id);
